### ISSUE TITLE
compile error with GHC 7.10.3

### ISSUE THREAD

**Issue by hvr** [m0rphism/printcess#4]
See below

```
In order, the following will be built (use -v for more details):
 - printcess-0.1.0.0 {printcess-0.1.0.0-inplace} (lib:printcess) (first run)
[1 of 1] Compiling Main             ( /tmp/matrix-worker/1480456263/dist-newstyle/build/x86_64-linux/ghc-7.10.3/printcess-0.1.0.0/setup/setup.hs, /tmp/matrix-worker/1480456263/dist-newstyle/build/x86_64-linux/ghc-7.10.3/printcess-0.1.0.0/setup/Main.o )
Linking /tmp/matrix-worker/1480456263/dist-newstyle/build/x86_64-linux/ghc-7.10.3/printcess-0.1.0.0/setup/setup ...
Configuring printcess-0.1.0.0...
Preprocessing library printcess-0.1.0.0...

src/Printcess/Config.hs:2:20:
    Cannot parse LANGUAGE pragma
    Expecting comma-separated list of language options,
    each starting with a capital letter
      E.g. {-# LANGUAGE TemplateHaskell, GADTs #-}

```

**Comment by m0rphism** [comment]
Hmm, that's odd. The code in question is

    {-# LANGUAGE
      TemplateHaskell, UnicodeSyntax
    #-}

Did the accepted syntax of `LANGUAGE` pragmas change over the last GHC versions?
My GHC 8.0.1 had no problems parsing.

I've reverted to more conventional syntax and pushed version 0.1.0.1:

    {-# LANGUAGE TemplateHaskell, UnicodeSyntax #-}

I hope this resolves the issue.

Thank you very much for your service, again! It's appreciated! :+1:

**Comment by hvr** [comment]
@m0rphism yes, it appears that GHC 8.0's parser/lexer has become more tolerant for pragmas... I wasn't aware of it :-)


However, I'm afraid the new release is still broken for a different reason now:

```
In order, the following will be built (use -v for more details):
 - printcess-0.1.0.1 {printcess-0.1.0.1-inplace} (lib:printcess) (first run)
[1 of 1] Compiling Main             ( /tmp/matrix-worker/1480460197/dist-newstyle/build/x86_64-linux/ghc-7.10.3/printcess-0.1.0.1/setup/setup.hs, /tmp/matrix-worker/1480460197/dist-newstyle/build/x86_64-linux/ghc-7.10.3/printcess-0.1.0.1/setup/Main.o )
Linking /tmp/matrix-worker/1480460197/dist-newstyle/build/x86_64-linux/ghc-7.10.3/printcess-0.1.0.1/setup/setup ...
Configuring printcess-0.1.0.1...
Preprocessing library printcess-0.1.0.1...

src/Printcess/Core.hs:10:8:
    Could not find module ‘Data.List.NonEmpty’
    It is a member of the hidden package ‘semigroups-0.18.2@BXwYYtsEMWZJSjSVzaBK2L’.
    Perhaps you need to add ‘semigroups’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘semigroups-0.18.2@HeLXC50ICe5E60uwTshObg’.
    Perhaps you need to add ‘semigroups’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘semigroups-0.18.2@4FDglYA96iQApZ7yU25BiE’.
    Perhaps you need to add ‘semigroups’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

PS: are you aware of https://github.com/hvr/multi-ghc-travis/blob/master/make_travis_yml_2.hs ?

**Comment by m0rphism** [comment]
Thanks, I forgot about `NonEmpty`... should be fixed now. :-)

I wasn't aware of the script, but was already wondering whether such a thing exists ;-)
Thanks for linking it. I'll give it a more thorough look when I find time.

I'll try to test these things in advance from now on!

**Comment by hvr** [comment]
@m0rphism thanks! the latest release passes the buildbot :-)

I went ahead and fixed up the meta-data on Hackage for the previous two releases to avoid the buildbot running into those failures again:

 - https://hackage.haskell.org/package/printcess-0.1.0.0/revisions/
 - https://hackage.haskell.org/package/printcess-0.1.0.1/revisions/

**Comment by m0rphism** [comment]
Excellent, thanks! :-)
